rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode

env:
  - ADAPTER=active_record
  - ADAPTER=mongoid

before_install:
  - gem --version
  - ruby -v
  - gem list
  
services: mongodb

matrix:
  allow_failures:
    - rvm: 2.0.0
